# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=60)),
                ('company_name', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('street', models.CharField(max_length=60)),
                ('home_number', models.CharField(max_length=12)),
                ('postal_code', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=20)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile')),
            ],
        ),
    ]
