# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 16:42
from __future__ import unicode_literals

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_remove_cart_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
