# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=499.99, max_digits=8)),
                ('image', models.ImageField(blank=True, default='products/default.jpg', null=True, upload_to=products.models.upload_image_path)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tags', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('sample_photos', models.ImageField(blank=True, default='products/default.jpg', null=True, upload_to=products.models.upload_image_path)),
            ],
            bases=('products.product',),
        ),
    ]
