# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='selled',
            field=models.BooleanField(default=False),
        ),
    ]
