# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180224_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Dalmierze', max_length=120),
        ),
    ]
