# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='uncategorized', max_length=120),
        ),
    ]
