# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180225_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('range', 'range'), ('half', 'half'), ('compact', 'compact'), ('medium', 'medium'), ('straps', 'straps'), ('buttons', 'buttons')], max_length=120, null=True),
        ),
    ]
