# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180225_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='serial_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('range', 'Aparaty dalmierzowe'), ('half', 'Aparaty połówkowe'), ('compact', 'Aparaty kompaktowe'), ('medium', 'Aparaty średnioformatowe'), ('straps', 'Paski'), ('buttons', 'Przyciski spustu')], max_length=120, null=True),
        ),
    ]
