# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20180227_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='serial_number',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
