# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20180227_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='quality',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='attribute',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
