# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20180228_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attribute',
        ),
        migrations.AddField(
            model_name='camera',
            name='set_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='attribute1',
            field=models.CharField(blank=True, choices=[('kolor czerwony', 'Aparaty czerwony'), ('pasek nadgarstkowy', 'pasek nadgarstkowy'), ('kolor niebieski', 'kolor niebieski')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='attribute2',
            field=models.CharField(blank=True, choices=[('kolor czerwony', 'Aparaty czerwony'), ('pasek nadgarstkowy', 'pasek nadgarstkowy'), ('kolor niebieski', 'kolor niebieski')], max_length=120, null=True),
        ),
    ]
