# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_polymorphic_ctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strap',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Product')),
                ('type', models.TextField(blank=True, max_length=20, null=True)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('products.product',),
        ),
    ]
