# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20180303_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='brand',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='model',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
    ]
