# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20180303_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strap',
            name='color',
        ),
        migrations.AddField(
            model_name='strap',
            name='model',
            field=models.CharField(blank=True, choices=[('black_short', 'krótki czarny'), ('brown_long', 'długi brązowy')], max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='strap',
            name='type',
            field=models.CharField(blank=True, choices=[('wrist', 'Pasek nadgarstkowy'), ('head', 'Pasek na szyję')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='button',
            name='color',
            field=models.CharField(blank=True, choices=[('black', 'czarny'), ('red', 'czerwony'), ('set', 'zestaw 4 kolorów')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='brand',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='model',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='Title', max_length=120),
        ),
    ]
