# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20180303_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
