# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20180303_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='temp_title', max_length=120),
        ),
    ]
