# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20180303_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='title',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='title',
        ),
        migrations.RemoveField(
            model_name='strap',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
