# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20180303_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='button',
            name='description',
            field=models.TextField(default='\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consectetur facilisis orci a sollicitudin. Nam tristique enim eu nisl sodales, vel consequat nunc dictum. Quisque malesuada diam sed finibus pellentesque. Nam eget ante egestas, tempus tellus pellentesque, semper mauris. Aliquam porttitor malesuada magna. Pellentesque cursus cursus ultrices. Aenean tincidunt efficitur felis, et accumsan nulla sodales sit amet.\n\nVivamus libero sapien, ultricies ac eleifend a, ultrices in lacus. Proin sodales iaculis pretium. Phasellus facilisis dictum nunc at consequat. Duis a nunc eget arcu fringilla imperdiet ut id leo. Sed euismod quis felis sed finibus. Vivamus commodo felis nisl, bibendum vehicula quam lacinia eget. Mauris enim sapien, porttitor nec interdum et, consectetur id magna. Aliquam a efficitur est. Morbi neque justo, rhoncus eget lacus dapibus, finibus tristique felis. Nam mollis leo et laoreet iaculis. Etiam euismod justo et ligula euismod volutpat.\n\nSed vel tristique purus. Praesent blandit scelerisque dolor. Vestibulum tristique velit risus, ut aliquam nisl fermentum non. Etiam lorem nisi, suscipit ut massa eget, commodo posuere arcu. Pellentesque eu velit mi. Sed tincidunt sollicitudin facilisis. Donec sit amet purus sit amet nunc gravida consectetur. Aenean lacus nibh, euismod sit amet sodales ac, auctor non urna. Quisque eget risus blandit, interdum neque nec, tincidunt sem. Vivamus et placerat ante. Sed id nisi malesuada, efficitur eros nec, ultricies ligula. Proin rutrum purus a congue consequat. Ut lobortis, purus id vestibulum interdum, augue ipsum tincidunt odio, non ultricies velit sem eget nisi. Quisque non felis eu lacus mattis mattis in congue ligula. Etiam orci tellus, feugiat in vulputate sit amet, tempor in tellus. Integer tincidunt eros nec diam placerat posuere.\n\nSed quis elit elit. Nam sollicitudin pellentesque lectus nec tristique. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam eu viverra massa. Donec egestas magna ac orci viverra tempus. Aenean elementum interdum semper. Cras dapibus finibus lobortis. Quisque id turpis quis neque pharetra pharetra. Phasellus rutrum leo in consectetur auctor. Quisque placerat rutrum quam non dapibus. Sed malesuada neque purus, quis luctus leo porttitor ut. Donec in erat nibh. Nam dignissim tempor nunc sit amet auctor. Nulla bibendum justo nec est porttitor, eu mollis ex elementum.\n\nPraesent dignissim justo ac nibh aliquet dapibus. Sed in faucibus turpis. Praesent tempor arcu eu ullamcorper consequat. Fusce luctus quam at sapien pharetra congue. Suspendisse a ornare ex, id maximus tellus. Nunc ut ipsum sed leo dapibus eleifend. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.\n\n'),
        ),
        migrations.AddField(
            model_name='camera',
            name='description',
            field=models.TextField(default='TO JEST OPIS KAMERY'),
        ),
        migrations.AddField(
            model_name='strap',
            name='description',
            field=models.TextField(default='\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consectetur facilisis orci a sollicitudin. Nam tristique enim eu nisl sodales, vel consequat nunc dictum. Quisque malesuada diam sed finibus pellentesque. Nam eget ante egestas, tempus tellus pellentesque, semper mauris. Aliquam porttitor malesuada magna. Pellentesque cursus cursus ultrices. Aenean tincidunt efficitur felis, et accumsan nulla sodales sit amet.\n\nVivamus libero sapien, ultricies ac eleifend a, ultrices in lacus. Proin sodales iaculis pretium. Phasellus facilisis dictum nunc at consequat. Duis a nunc eget arcu fringilla imperdiet ut id leo. Sed euismod quis felis sed finibus. Vivamus commodo felis nisl, bibendum vehicula quam lacinia eget. Mauris enim sapien, porttitor nec interdum et, consectetur id magna. Aliquam a efficitur est. Morbi neque justo, rhoncus eget lacus dapibus, finibus tristique felis. Nam mollis leo et laoreet iaculis. Etiam euismod justo et ligula euismod volutpat.\n\nSed vel tristique purus. Praesent blandit scelerisque dolor. Vestibulum tristique velit risus, ut aliquam nisl fermentum non. Etiam lorem nisi, suscipit ut massa eget, commodo posuere arcu. Pellentesque eu velit mi. Sed tincidunt sollicitudin facilisis. Donec sit amet purus sit amet nunc gravida consectetur. Aenean lacus nibh, euismod sit amet sodales ac, auctor non urna. Quisque eget risus blandit, interdum neque nec, tincidunt sem. Vivamus et placerat ante. Sed id nisi malesuada, efficitur eros nec, ultricies ligula. Proin rutrum purus a congue consequat. Ut lobortis, purus id vestibulum interdum, augue ipsum tincidunt odio, non ultricies velit sem eget nisi. Quisque non felis eu lacus mattis mattis in congue ligula. Etiam orci tellus, feugiat in vulputate sit amet, tempor in tellus. Integer tincidunt eros nec diam placerat posuere.\n\nSed quis elit elit. Nam sollicitudin pellentesque lectus nec tristique. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam eu viverra massa. Donec egestas magna ac orci viverra tempus. Aenean elementum interdum semper. Cras dapibus finibus lobortis. Quisque id turpis quis neque pharetra pharetra. Phasellus rutrum leo in consectetur auctor. Quisque placerat rutrum quam non dapibus. Sed malesuada neque purus, quis luctus leo porttitor ut. Donec in erat nibh. Nam dignissim tempor nunc sit amet auctor. Nulla bibendum justo nec est porttitor, eu mollis ex elementum.\n\nPraesent dignissim justo ac nibh aliquet dapibus. Sed in faucibus turpis. Praesent tempor arcu eu ullamcorper consequat. Fusce luctus quam at sapien pharetra congue. Suspendisse a ornare ex, id maximus tellus. Nunc ut ipsum sed leo dapibus eleifend. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.\n\n'),
        ),
    ]
