# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20180304_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='model',
            field=models.CharField(blank=True, choices=[('black', 'czarny'), ('red', 'czerwony'), ('set', 'zestaw 3 kolorów')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='serial_number',
            field=models.CharField(blank=True, default='000001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='strap',
            name='type',
            field=models.CharField(blank=True, choices=[('wrist', 'Nadgarstkowy'), ('head', 'Na szyję')], max_length=120, null=True),
        ),
    ]
