# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20180305_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='set_description',
            field=models.TextField(blank=True, default='\naparat &\npokrowiec neoprenowy &\noryginalny pokrowiec &\n', max_length=200, null=True),
        ),
    ]
