# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20180306_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.ImageField(blank=True, default='products/sample.jpg', null=True, upload_to=products.models.upload_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='products/default.jpg', null=True, upload_to=products.models.upload_image_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='camera',
            name='sample_photos',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Product'),
        ),
        migrations.AddField(
            model_name='camerasamples',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='products.Camera'),
        ),
    ]
