# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20180313_1939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CameraSamples',
            new_name='CameraSample',
        ),
    ]
