# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20180313_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='products/default.jpg', upload_to=products.models.upload_image_path),
        ),
    ]
