# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_auto_20180313_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='info_links',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
