# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_camera_info_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='serial_number',
            field=models.CharField(blank=True, default='000', max_length=20, null=True),
        ),
    ]
