# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_auto_20180603_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(default='products/default_min.jpg', max_length=500, upload_to=products.models.upload_image_path),
        ),
    ]
