# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_productimage_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camerasample',
            old_name='sample',
            new_name='image',
        ),
        migrations.AddField(
            model_name='camerasample',
            name='thumbnail',
            field=models.ImageField(default='products/sample.jpg', max_length=500, upload_to=products.models.upload_image_path),
        ),
    ]
