# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20180608_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerasample',
            name='image',
            field=models.ImageField(blank=True, default='default_min.jpg', null=True, upload_to=products.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='camerasample',
            name='thumbnail',
            field=models.ImageField(default='default_min.jpg', max_length=500, upload_to=products.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='default_min.jpg', upload_to=products.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(default='default_min.jpg', max_length=500, upload_to=products.models.upload_image_path),
        ),
    ]
