# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_auto_20180721_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strap',
            name='model',
            field=models.CharField(blank=True, choices=[('rope', 'sznurowany'), ('leather_thin_black', 'skórzany cienki czarny'), ('leather_thin_brown', 'skórzany cienki brązowy'), ('leather_medium_black', 'skórzany średni czarny'), ('leather_medium_brown', 'skórzany średni brązowy'), ('leather_thick_black', 'skórzany gruby czarny'), ('leather_thick_brown_dark', 'skórzany gruby ciemny brązowy'), ('leather_thick_brown_light', 'skórzany gruby jasny brązowy')], max_length=120, null=True),
        ),
    ]
