# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_auto_20180822_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='button',
            name='description_pl',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='description_en',
            field=models.TextField(default=' A camera is an optical instrument for recording or capturing images, which may be stored locally, transmitted to another location, or both. The images may be individual still photographs or sequences of images constituting videos or movies. The camera is a remote sensing device as it senses subjects without any contact . The word camera comes from camera obscura, which means "dark chamber" and is the Latin name of the original device for projecting an image of external reality onto a flat surface. The modern photographic camera evolved from the camera obscura. The functioning of the camera is very similar to the functioning of the human eye. The first permanent photograph of a camera image was made in 1826 by Joseph Nicéphore Niépce.\n', null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='description_pl',
            field=models.TextField(default=' A camera is an optical instrument for recording or capturing images, which may be stored locally, transmitted to another location, or both. The images may be individual still photographs or sequences of images constituting videos or movies. The camera is a remote sensing device as it senses subjects without any contact . The word camera comes from camera obscura, which means "dark chamber" and is the Latin name of the original device for projecting an image of external reality onto a flat surface. The modern photographic camera evolved from the camera obscura. The functioning of the camera is very similar to the functioning of the human eye. The first permanent photograph of a camera image was made in 1826 by Joseph Nicéphore Niépce.\n', null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='set_description_en',
            field=models.TextField(blank=True, default=' aparat &\npokrowiec neoprenowy &\noryginalny pokrowiec &\n', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='set_description_pl',
            field=models.TextField(blank=True, default=' aparat &\npokrowiec neoprenowy &\noryginalny pokrowiec &\n', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='spec_table_en',
            field=models.TextField(blank=True, default=' obiektyw @ 40 mm F:1.7 &\nnegatyw @ 35mm 25-800 ASA &\nmigawka @ 1/4 - 1/500 s &\ntryb pracy @ priorytet czasu &\nwizjer @ 0.6X, korekta paralaksy &\nbateria @ 1.35V PX625 &\nstopka lampy @ tak &\nwymiary @ 120 × 75 × 60 &\nwaga @ 620 g &\n', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='spec_table_pl',
            field=models.TextField(blank=True, default=' obiektyw @ 40 mm F:1.7 &\nnegatyw @ 35mm 25-800 ASA &\nmigawka @ 1/4 - 1/500 s &\ntryb pracy @ priorytet czasu &\nwizjer @ 0.6X, korekta paralaksy &\nbateria @ 1.35V PX625 &\nstopka lampy @ tak &\nwymiary @ 120 × 75 × 60 &\nwaga @ 620 g &\n', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='timestamp_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='timestamp_pl',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_pl',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='strap',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='strap',
            name='description_pl',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
