# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_auto_20180822_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='timestamp_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='timestamp_pl',
        ),
    ]
