# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_auto_20180826_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promo_price',
        ),
    ]
