# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=120)),
                ('country_code', models.CharField(max_length=120)),
                ('country_name', models.CharField(max_length=120)),
                ('region_code', models.CharField(max_length=120)),
                ('region_name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('zip_code', models.CharField(max_length=120)),
                ('latitude', models.CharField(max_length=120)),
                ('longitude', models.CharField(max_length=120)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
