# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='date',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
