# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-01 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0004_auto_20181102_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocation',
            name='viewed_object',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
