# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 05:40
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0047_auto_20180901_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_PLN_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='PLN', editable=False, max_length=3)),
                ('regular_PLN', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=8)),
                ('regular_USD_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='USD', editable=False, max_length=3)),
                ('regular_USD', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='USD', max_digits=8, null=True)),
                ('regular_EUR_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('regular_EUR', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='EUR', max_digits=8, null=True)),
                ('promo_PLN_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='PLN', editable=False, max_length=3)),
                ('promo_PLN', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, max_digits=8, null=True)),
                ('promo_USD_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='USD', editable=False, max_length=3)),
                ('promo_USD', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='USD', max_digits=8, null=True)),
                ('promo_EUR_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('promo_EUR', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='EUR', max_digits=8, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_PLN_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='PLN', editable=False, max_length=3)),
                ('local_PLN', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=8)),
                ('local_USD_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='USD', editable=False, max_length=3)),
                ('local_USD', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='USD', max_digits=8, null=True)),
                ('local_EUR_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('local_EUR', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='EUR', max_digits=8, null=True)),
                ('international_PLN_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='PLN', editable=False, max_length=3)),
                ('international_PLN', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=8)),
                ('international_USD_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='USD', editable=False, max_length=3)),
                ('international_USD', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='USD', max_digits=8, null=True)),
                ('international_EUR_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('international_EUR', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='EUR', max_digits=8, null=True)),
            ],
        ),
    ]
