# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-15 18:15
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingprice',
            name='self_EUR',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=8),
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='self_EUR_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='self_PLN',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='self_PLN_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='self_USD',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='USD', max_digits=8),
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='self_USD_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('PLN', 'PLN zł'), ('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
    ]
