# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='logged_user_promo',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
