# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_logged_user_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='logged_user_promo',
            field=models.IntegerField(default=0),
        ),
    ]
