# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180224_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Stworzone'), ('done', 'Zatwierdzone'), ('paid', 'Zapłacone'), ('shipped', 'Wysłane'), ('refunded', 'Zwrot')], default='created', max_length=20),
        ),
    ]
