# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180308_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
