# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-26 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='logged_user_promo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
