# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-08 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180901_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='PLN', max_length=3),
        ),
    ]
