# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(default='local', max_length=20),
        ),
    ]
