# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_shipping_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_info',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
