# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_objectviewed_guest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectviewed',
            name='ip_address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
