# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infobox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobox',
            name='message_de',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='infobox',
            name='message_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='infobox',
            name='message_es',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='infobox',
            name='message_pl',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
