# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infobox', '0002_auto_20180819_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infobox',
            name='message_de',
        ),
        migrations.RemoveField(
            model_name='infobox',
            name='message_es',
        ),
    ]
